language: python
install: tests/install.sh
script: tests/test.sh
matrix:
    include:
        - python: "2.6"
        - python: "2.7"
        - python: "3.2"
        - python: "3.3"
        - python: "3.4"
        - python: "pypy"
        - python: "pypy3"
        - python: "2.6"
          env: >-
            USE_UCS2_PYTHON=1
            UCS2_PYTHON_VARIANT="2.6"
        - python: "2.7"
          env: >-
            USE_UCS2_PYTHON=1
            UCS2_PYTHON_VARIANT="2.7"

# vim: et
